### PR TITLE
Make changes to make things work in modern distros.

### PR DESCRIPTION
**Pull request by poikilos**
- Use autotools for wmglobe
- Fix multiple definition errors in wmglobe (by @OldCoder)

### CODE REVIEW

**Comment by d-torrance** [comment]
Thanks for these patches!  However, this repository is just used for the issue tracker and hosting dockapps.net.  The main code is hosted at https://repo.or.cz/dockapps, and patches should be submitted to wmaker-dev@googlegroups.com using `git send-email`.  Could you do that instead?

Thanks!

**Comment by poikilos** [comment]
Ok, I sent the patches that way.

**Comment by OldCoder** [comment]
On 09/26/2021 05:15 AM, Doug Torrance wrote:
> Thanks for these patches! However, this repository is just used for the 
> issue tracker and hosting dockapps.net. The main code is hosted at 
> https://repo.or.cz/dockapps, and patches should be submitted to 
> ***@***.*** using |git send-email|. Could you do that instead?

I'm the original source for whatever you received. However, I'm not 
clear about what happened. I haven't submitted patches to the "dockapps" 
project in recent months.

I did work yesterday with the person that I've Cc'd on getting dockapps 
to build in his copy of Devuan 4. Did he submit some of my patches to you?

Regarding the suggestion that we submit patches to a mailing list, 
thanks for the information that you provided.

**Comment by OldCoder** [comment]
OldCoder, I submitted some patches with you as a co-author. The upstream 
repo had the same issues we had.

**Comment by poikilos** [comment]
> OldCoder, I submitted some patches with you as a co-author. The upstream repo had the same issues we had.
> […](#)
> On 9/26/21 3:25 PM, Robert Kiraly wrote: On 09/26/2021 05:15 AM, Doug Torrance wrote: > Thanks for these patches! However, this repository is just used for > the issue tracker and hosting dockapps.net. The main code is hosted > at https://repo.or.cz/dockapps, and patches should be submitted to > ***@***.*** using |git send-email|. Could you do that > instead? I'm the original source for whatever you received. However, I'm not clear about what happened. I haven't submitted patches to the "dockapps" project in recent months. I did work yesterday with the person that I've Cc'd on getting dockapps to build in his copy of Devuan 4. Did he submit some of my patches to you? Regarding the suggestion that we submit patches to a mailing list, thanks for the information that you provided.

^ That was from me via the mailing list. It posted here as OldCoder for some reason, perhaps since I was originally a CC. The automation of that may need a tweak to utilize the sender correctly.

**Pull request closed without merging**
